interim commit to comment out @Inject in seven RedisModule methods
This seems to get rid of the error we get in our project's maven integration tests
 BeanCreationException: Could not autowire method: ...RedisModule.set(...)

Also need to supply a dummy muleEvent-ref in the
 mule-module-redis.xml.sample
now that there is no autowire for those methods, otherwise "mvn clean package" fails.